name: Build and Publish Website
on: 
    push:
        branch:
            - main
    schedule:
      - cron: "0 0,6,12,18 * * *"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
         token: ${{ secrets.TOKEN }}
         # submodules: recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.85.0"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: DataForNerds/website
          publish_dir: ./public
          # keep_files: true
          user_name: "GitHub Actions"
          user_email: "noreply@datafornerds.io"
          publish_branch: main
          cname: datafornerds.io